<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.0 setup script
 * Date: Mon, 27 Jun 2022 14:08:45 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: gab.ckubzlnmrmhc.us-east-2.rds.amazonaws.com [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'gab.ckubzlnmrmhc.us-east-2.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'H1A,XJ+[ux2[HrR]\\)NZ)mv#WMeQyK`6';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

